name: monobank_api
description: >
  Simplifies interaction with public Monobank API

  Supports getting currencies and grabbing statement

version: 2.0.0
homepage: https://github.com/Sominemo/monobank_api

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.5
