name: monobank_api
description: >
  Simplifies interaction with public Monobank API

  Supports getting currencies and grabbing statement

version: 1.4.1
homepage: https://github.com/Sominemo/monobank_api

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
