name: monobank_api
description: >
    Simplifies interaction with public Monobank API

    Supports getting currencies and statement info, includes currency and MCC datasets

version: 2.1.0
repository: https://github.com/Sominemo/monobank_api
issue_tracker: https://github.com/Sominemo/monobank_api/issues

environment:
    sdk: ">=2.17.0 <4.0.0"

dependencies:
    http: ^1.1.0

dev_dependencies:
    lints: ^3.0.0
    test: ^1.16.5
