name: monobank_api
description: >
  Simplifies interaction with public Monobank API

  Supports getting currencies and grabbing statement

version: 1.2.1
homepage: https://github.com/Sominemo/monobank_api

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
